import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
const inter = Inter({ subsets: ['latin'] });
import dynamic from 'next/dynamic';

const Stage = dynamic(() => import('../../components/Stage/Stage'), {
  ssr: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        <div>
          <h1>Word Vacuum</h1>
        </div>
        <Stage />
        <div>
          <div>Footer</div>
        </div>
      </div>
    </>
  );
}
