import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from './index.module.css';
const inter = Inter({ subsets: ['latin'] });
import dynamic from 'next/dynamic';

const Stage = dynamic(() => import('../components/Stage/.back'), {
  ssr: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <div className={styles.row}>
          <h4>Create</h4>
        </div>
       <div className={styles.row}>
       <a href='/game/1234'>Click to start game</a>
       </div>
      </div>
    </>
  );
}
